[project]
name = "malachite"
version = "0.1.0"
description = "email domain banlist manager"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.29.0",
    "dnspython>=2.7.0",
    "ircrobots>=0.6.6",
]

[tool.pyright]
reportPrivateImportUsage = "none"
